version: '3.8'

services:
  # Node server for running SCIM verification tests
  scimserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: ["npx", "nodemon", "server.js"]
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - scim-network
    restart: unless-stopped

  # VitePress documentation site
  vitepress:
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/site/
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    networks:
      - scim-network
    restart: unless-stopped

networks:
  scim-network:
    driver: bridge